package database.relations;

public enum RelationTypes implements RelationTypesInterface {

	ARRAYACCESS_EXPR, ARRAYACCESS_INDEX,

	ASSERT_CONDITION, ASSERT_DETAIL, ASSIGNMENT_LHS,

	ASSIGNMENT_RHS, BINOP_LHS,

	BINOP_RHS, CASE_EXPR, CASE_STATEMENTS, CAST_ENCLOSES,

	CAST_TYPE, CATCH_BLOCK, CATCH_PARAM, COMPOUND_ASSIGNMENT_LHS,

	COMPOUND_ASSIGNMENT_RHS, CONDITIONAL_EXPR_CONDITION,

	CONDITIONAL_EXPR_ELSE, CONDITIONAL_EXPR_THEN, CU_PACKAGE_DEC,

	DECLARES_FIELD, DECLARES_METHOD,DECLARES_CONSTRUCTOR, DOWHILE_CONDITION,

	ENCLOSES, ERRONEOUS_NODE_CAUSED_BY, ENCLOSES_EXPR,

	FOREACH_EXPR, FOREACH_STATEMENT, FOREACH_VAR,

	FORLOOP_CONDITION, FORLOOP_INIT, FORLOOP_STATEMENT, FORLOOP_UPDATE,

	HAS_ANNOTATIONS, HAS_ANNOTATIONS_ARGUMENTS, HAS_ANNOTATIONS_TYPE,

	HAS_CLASS_EXTENDS, HAS_CLASS_IMPLEMENTS, HAS_CLASS_MODIFIERS, HAS_CLASS_TYPEPARAMETERS,

	HAS_DEFAULT_VALUE,

	HAS_METHODDECL_BODY, HAS_METHODDECL_DEFAULT_VALUE, HAS_METHODDECL_MODIFIERS, HAS_METHODDECL_PARAMETERS,

	HAS_METHODDECL_RETURNS, HAS_METHODDECL_THROWS, HAS_METHODDECL_TYPEPARAMETERS, HAS_RECEIVER_PARAMETER, HAS_STATIC_INIT, HAS_THIS_REFERENCE,

	HAS_TYPE_DEC, HAS_VARIABLEDECL_INIT, HAS_VARIABLEDECL_MODIFIERS, HAS_VARIABLEDECL_TYPE,

	IF_CONDITION, IF_ELSE, IF_THEN, IMPORTS,

	INSTANCEOF_EXPR, INSTANCEOF_TYPE, INTERSECTION_COMPOSED_BY, IS_SUBTYPE_EXTENDS, IS_SUBTYPE_IMPLEMENTS,

	LABELED_STATEMENT, LAMBDA_EXPRESSION_BODY, LAMBDA_EXPRESSION_PARAMETERS, MEMBER_REFERENCE_EXPRESSION, MEMBER_REFERENCE_TYPE_ARGUMENTS, MEMBER_SELECT_EXPR,

	MEMBER_SELECT_NAME, METHODINVOCATION_ARGUMENTS, METHODINVOCATION_METHOD_SELECT, METHODINVOCATION_TYPE_ARGUMENTS, NEW_CLASS_ARGUMENTS, NEW_CLASS_BODY,

	NEW_CLASS_TYPE_ARGUMENTS, NEWARRAY_DIMENSION, NEWARRAY_INIT, NEWARRAY_TYPE, NEWCLASS_ENCLOSING_EXPRESSION, NEWCLASS_IDENTIFIER,

	PARAMETERIZEDTYPE_TYPE, PARAMETERIZEDTYPE_TYPEARGUMENTS, PARENTHESIZED_ENCLOSES, RETURN_EXPR,

	SWITCH_ENCLOSES_CASES, SWITCH_EXPR, SYNCHRONIZED_BLOCK, SYNCHRONIZED_EXPR, THROW_EXPR, TRY_BLOCK,

	TRY_CATCH, TRY_FINALLY, TRY_RESOURCES, TYPE_PER_ELEMENT, TYPEPARAMETER_EXTENDS, UNARY_ENCLOSES,

	UNDERLYING_TYPE, UNION, WHILE_CONDITION, WILDCARD_BOUND, INITIALIZATION_EXPR

}
