package es.uniovi.reflection.progquery.database.nodes;

import org.neo4j.graphdb.Label;

public enum NodeCategory implements Label {
	//Categoria para annotation, package, compilation-unit??
	PQ_NODE, //TOP Category
	AST_NODE, CFG_NODE, PDG_NODE,TYPE_NODE, PACKAGE_NODE,
	
	
	AST_TYPE,
	STATEMENT, 
	//BRANCH_STATEMENT, CONDITIONAL_STATEMENT??, UNCONDITIONAL_STATEMENT??
	
	EXPRESSION, 
	DEFINITION,  	//SUPERCLASS FOR DECLARATION,TYPE_DEFINITION,CALLABLE_DEF
	TYPE_DEFINITION,//SUPERCLASS FOR CLASS INTERFACE ENUM
	VARIABLE_DEF, //SUPERCLASS FOR PARAM_DEC, VAR_DEC, ATTR_DEC
	LOCAL_DEF,//SUPERCLASS FOR PARAM_DEC, VAR_DEC,
	//MEMBER_DEF?? //SUPERCLASS FOR ATTR_DEC, CALLABLE_DEF, MEMBER_CLASS
	CALLABLE_DEF 
	// SUPERCLASS FOR CONSTRUCTOR AND METHODS
	, CALL //SUPERCLASS FOR METHOD_INV AND NEW_
	, LVALUE
	
	
}
