package relations;

public enum NodeTypes {

	CONSTRUCTOR_DEC, METHOD_DEC, ANNOTATION_TYPE, ANNOTATION, ARRAY_ACCESS, ARRAY_TYPE, ASSERT_STATEMENT, ASSIGNMENT, BINARY_OPERATION, BLOCK, BREAK_STATEMENT, CASE_STATEMENT, CATCH_BLOCK, INTERFACE_DECLARATION, ENUM_DECLARATION, CLASS_DECLARATION, COMPOUND_ASSIGNMENT, CONDITIONAL_EXPRESSION, CONTINUE_STATEMENT, ERRONEOUS_NODE, ENHANCED_FOR, IDENTIFIER, IF_STATEMENT, IMPORT, INSTANCE_OF, INTERSECTION_TYPE, LABELED_STATEMENT, LAMBDA_EXPRESSION, LITERAL, MEMBER_REFERENCE, MEMBER_ACCESS, METHOD_INVOCATION, MODIFIERS, NEW_ARRAY, NEW_INSTANCE, PARAMETRIZED_TYPE, PRIMITIVE_TYPE, PARENTHESIZED_EXPRESSION, RETURN_STATEMENT, SWITCH_STATEMENT, SYNCHRONIZED_BLOCK, TRY_BLOCK, THROW_STATEMENT, TYPE_CAST, TYPE_PARAM, WILDCARD, UNARY_OPERATION, PARAMETER_DEC, ATTR_DEC, VAR_DEC, UNION_TYPE, COMPILATION_UNIT

}
